In [5]:
# create two python lists:
list_1 = list(range(1000))
list_2 = list(range(2000, 3000))
list_2

[2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024,
 2025,
 2026,
 2027,
 2028,
 2029,
 2030,
 2031,
 2032,
 2033,
 2034,
 2035,
 2036,
 2037,
 2038,
 2039,
 2040,
 2041,
 2042,
 2043,
 2044,
 2045,
 2046,
 2047,
 2048,
 2049,
 2050,
 2051,
 2052,
 2053,
 2054,
 2055,
 2056,
 2057,
 2058,
 2059,
 2060,
 2061,
 2062,
 2063,
 2064,
 2065,
 2066,
 2067,
 2068,
 2069,
 2070,
 2071,
 2072,
 2073,
 2074,
 2075,
 2076,
 2077,
 2078,
 2079,
 2080,
 2081,
 2082,
 2083,
 2084,
 2085,
 2086,
 2087,
 2088,
 2089,
 2090,
 2091,
 2092,
 2093,
 2094,
 2095,
 2096,
 2097,
 2098,
 2099,
 2100,
 2101,
 2102,
 2103,
 2104,
 2105,
 2106,
 2107,
 2108,
 2109,
 2110,
 2111,
 2112,
 2113,
 2114,
 2115,
 2116,
 2117,
 2118,
 2119,
 2120,
 2121,
 2122,
 2123,
 2124,
 2125,
 2126,
 2127,
 2128,
 2129,
 2130,
 2131,
 2132,
 2133,
 2134,
 2135,
 2136,
 2137,
 2138,
 2139,
 2140,
 2141,
 2142,

Import NumPy and Create two numpy arrays using the two Python lists:

In [6]:
import  numpy as np

In [7]:
arr_1 = np.array(list_1)
arr_2 = np.array(list_2)

In [8]:
arr_1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

Define a function that will perform element wise addition of two Python lists.

In [9]:
def list_sum(l,l2):
    new_list = []
    for item in range(len(l)):
        new_list.append(l[item] + l2[item])
    return new_list

In [10]:
lst = list_sum(list_1, list_2)

Define a function that will perform element wise addition of two NumPy arrays.

In [11]:
# def array_sum(a, b):
#     new_array = []
#     for item in a:
#         new_array.append(a[item] + b[item])
#     return new_array

In [12]:
def array_sum():
    return arr_1 + arr_2

In [13]:
array_sum()

array([2000, 2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016, 2018, 2020,
       2022, 2024, 2026, 2028, 2030, 2032, 2034, 2036, 2038, 2040, 2042,
       2044, 2046, 2048, 2050, 2052, 2054, 2056, 2058, 2060, 2062, 2064,
       2066, 2068, 2070, 2072, 2074, 2076, 2078, 2080, 2082, 2084, 2086,
       2088, 2090, 2092, 2094, 2096, 2098, 2100, 2102, 2104, 2106, 2108,
       2110, 2112, 2114, 2116, 2118, 2120, 2122, 2124, 2126, 2128, 2130,
       2132, 2134, 2136, 2138, 2140, 2142, 2144, 2146, 2148, 2150, 2152,
       2154, 2156, 2158, 2160, 2162, 2164, 2166, 2168, 2170, 2172, 2174,
       2176, 2178, 2180, 2182, 2184, 2186, 2188, 2190, 2192, 2194, 2196,
       2198, 2200, 2202, 2204, 2206, 2208, 2210, 2212, 2214, 2216, 2218,
       2220, 2222, 2224, 2226, 2228, 2230, 2232, 2234, 2236, 2238, 2240,
       2242, 2244, 2246, 2248, 2250, 2252, 2254, 2256, 2258, 2260, 2262,
       2264, 2266, 2268, 2270, 2272, 2274, 2276, 2278, 2280, 2282, 2284,
       2286, 2288, 2290, 2292, 2294, 2296, 2298, 23

Notice the time taken by both the functions: list and array

In [14]:
# import timer from timeit library
from timeit import Timer

In [15]:
timer_1 = Timer("lst",
                "from __main__ import lst")

In [16]:
print("Pure python: ", timer_1.timeit(1000))

Pure python:  1.409999999779643e-05


In [17]:
timer_2 = Timer("array_sum()",
                "from __main__ import array_sum")

In [18]:
print("Numpy version: ", timer_2.timeit(1000))

Numpy version:  0.0023484000000024707


## observation:
- Numpy is significantly faster than Python

In [19]:
lst_new = np.arange(2, 13, 2)

In [20]:
lst_new

array([ 2,  4,  6,  8, 10, 12])

In [21]:
arr = np.array([
    [1,2,4],
    [8,45,34],
    [34,36,67]
])

In [22]:
arr

array([[ 1,  2,  4],
       [ 8, 45, 34],
       [34, 36, 67]])

In [23]:
array_1 = np.arange(10)

In [24]:
array_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# The zeros() function creates an n-dimensional array of zeros.
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
# linspace () generates values which are equally spaced from each other
arr_new = np.linspace(start=10, stop=40, num=40)

In [28]:
arr_new

array([10.        , 10.76923077, 11.53846154, 12.30769231, 13.07692308,
       13.84615385, 14.61538462, 15.38461538, 16.15384615, 16.92307692,
       17.69230769, 18.46153846, 19.23076923, 20.        , 20.76923077,
       21.53846154, 22.30769231, 23.07692308, 23.84615385, 24.61538462,
       25.38461538, 26.15384615, 26.92307692, 27.69230769, 28.46153846,
       29.23076923, 30.        , 30.76923077, 31.53846154, 32.30769231,
       33.07692308, 33.84615385, 34.61538462, 35.38461538, 36.15384615,
       36.92307692, 37.69230769, 38.46153846, 39.23076923, 40.        ])

In [29]:
# Write a Python program to create a NumPy array based on the following list:
list = [2, 5, 8, 6, 4, 12, 16, 15]
new_array = np.array(list)
new_array

array([ 2,  5,  8,  6,  4, 12, 16, 15])

In [30]:
new_array.shape

(8,)

In [31]:
new_array.ndim

1

Write a Python program to create an array of elements as per the below condition.
- The array must start with 17
- The array must end at 31
- The values in the array must be equally spaced or linearly spaced
- The array should have 50 samples/values in it.


In [32]:
np.linspace(start=17,stop=31, num=50)

array([17.        , 17.28571429, 17.57142857, 17.85714286, 18.14285714,
       18.42857143, 18.71428571, 19.        , 19.28571429, 19.57142857,
       19.85714286, 20.14285714, 20.42857143, 20.71428571, 21.        ,
       21.28571429, 21.57142857, 21.85714286, 22.14285714, 22.42857143,
       22.71428571, 23.        , 23.28571429, 23.57142857, 23.85714286,
       24.14285714, 24.42857143, 24.71428571, 25.        , 25.28571429,
       25.57142857, 25.85714286, 26.14285714, 26.42857143, 26.71428571,
       27.        , 27.28571429, 27.57142857, 27.85714286, 28.14285714,
       28.42857143, 28.71428571, 29.        , 29.28571429, 29.57142857,
       29.85714286, 30.14285714, 30.42857143, 30.71428571, 31.        ])

In [33]:
# a list of programming languages
['Python', 'C++', 'JavaScript']

['Python', 'C++', 'JavaScript']

In [34]:
# list of integers
my_list = [1, 2, 3]

In [35]:
# empty list
lst = []

In [36]:
# list with mixed data types
my_list = [9, "Espanol", 4.6, ['a','b','c']]
my_list

[9, 'Espanol', 4.6, ['a', 'b', 'c']]

In [37]:
# nested list
nested_list = ["mouse", [8, 4, 6], ['a'], ['joy', 'deb']]


In [38]:
nested_list

['mouse', [8, 4, 6], ['a'], ['joy', 'deb']]

# Arrays
- Similar to a list, an array is also a data structure which can hold more than one value at a time
- However, an array can only hold a collection of ordered elements of the same data type.

In [39]:
heights = [165, 170, 171, 180, 189, 178]
print(type(heights))

heights_np = np.array(heights)
print(type(heights_np))

<class 'list'>
<class 'numpy.ndarray'>


In [40]:
weights = np.array([[50, 45, 56, 78],
                    [78, 89, 59, 90],
                    [89, 78, 69, 70],
                    [67, 69, 89, 70],
                    [90,89, 80, 84],
                    [89, 59, 90, 78]]
                   )
print(weights)

[[50 45 56 78]
 [78 89 59 90]
 [89 78 69 70]
 [67 69 89 70]
 [90 89 80 84]
 [89 59 90 78]]


In [41]:
weights.ndim  # it is a dimensional array

2

In [42]:
weights.shape   # it has 6 rows and 4 columns

(6, 4)

In [43]:
weights.size  # it has 24 elements


24

In [44]:
weights.dtype    # int32 dtypes because each element of the array is a 32-bit (4-byte) integer 

dtype('int32')

In [45]:
weights.strides

(16, 4)

strides of (16, 4) since 16 bytes (4 integers of 4 bytes in the rows) are needed to store each row in memory and 4 bytes (1 integer per column) to store each column in memory.

In [46]:
a  = np.array(42)
a.ndim

0

In [47]:
b = np.array([1, 2, 3, 4, 5])
b.ndim

1

In [48]:
c = np.array([[1, 2, 3], [4, 5, 6]])
c.ndim

2

In [49]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [50]:
# zeros(shape=(n,m)) : Allows to create a zero-array with the shape (n rows, m columns)
x = np.zeros(shape=(5,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
# full(shape=(n,m), fill_value=f): Allows to create an array with the shape (n rows,m columns), where all positions have the value f.?

np.full(shape=(6,4),fill_value=6, dtype=complex)   ## Creating an array of complex type having constant values

array([[6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j]])

In [52]:
np.full(shape=(6,4),fill_value=6, dtype='int32')

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [53]:
# Create an array with random values
np.random.randint(4,100, size=34)

array([27, 34, 41, 32, 19, 95, 55, 35, 70, 75, 10, 57, 26, 37, 12, 57, 62,
       73, 71, 78,  9, 70, 35, 12, 72, 80, 67, 98, 32, 83, 78, 24, 28, 85])

In [54]:
np.random.random((4,6))

array([[0.30297897, 0.84918159, 0.00497463, 0.35299137, 0.92466249,
        0.93826398],
       [0.86705403, 0.89031139, 0.39309698, 0.48613574, 0.34762874,
        0.60105226],
       [0.85643762, 0.02677233, 0.98305192, 0.44867214, 0.77093804,
        0.53005415],
       [0.91711423, 0.34602487, 0.89719048, 0.44911143, 0.49073982,
        0.7475805 ]])

In [55]:
np.arange(100, 15000,1000)

array([  100,  1100,  2100,  3100,  4100,  5100,  6100,  7100,  8100,
        9100, 10100, 11100, 12100, 13100, 14100])

In [56]:
# Create a sequence of 10 values in range 0 to 5
np.linspace(0,5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [57]:
# Reshaping 3X4 array to 2X2X3 array
arr = np.array([[50, 45, 56, 78],[78, 89, 59, 90],[89, 78, 69, 70],[67, 69, 89, 70],[90,89, 80, 84],[89, 59, 90, 78]])
arr

array([[50, 45, 56, 78],
       [78, 89, 59, 90],
       [89, 78, 69, 70],
       [67, 69, 89, 70],
       [90, 89, 80, 84],
       [89, 59, 90, 78]])

In [58]:
new_arr = arr.reshape(2,6,2)

In [59]:
new_arr

array([[[50, 45],
        [56, 78],
        [78, 89],
        [59, 90],
        [89, 78],
        [69, 70]],

       [[67, 69],
        [89, 70],
        [90, 89],
        [80, 84],
        [89, 59],
        [90, 78]]])

In [60]:
# flatten array
arr

array([[50, 45, 56, 78],
       [78, 89, 59, 90],
       [89, 78, 69, 70],
       [67, 69, 89, 70],
       [90, 89, 80, 84],
       [89, 59, 90, 78]])

In [61]:
arr.flatten()

array([50, 45, 56, 78, 78, 89, 59, 90, 89, 78, 69, 70, 67, 69, 89, 70, 90,
       89, 80, 84, 89, 59, 90, 78])

In [62]:
# appending an element in to the array
np.append(new_arr, 14)

array([50, 45, 56, 78, 78, 89, 59, 90, 89, 78, 69, 70, 67, 69, 89, 70, 90,
       89, 80, 84, 89, 59, 90, 78, 14])

In [63]:
lst = [1,3,5,6,7,8]
np.append(new_arr, lst)     # it is possible to append python list to numpy array

array([50, 45, 56, 78, 78, 89, 59, 90, 89, 78, 69, 70, 67, 69, 89, 70, 90,
       89, 80, 84, 89, 59, 90, 78,  1,  3,  5,  6,  7,  8])

In [64]:
# append method directly doesnt work on the array    unlike list
new_arr.append(5)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [ ]:
np.delete(new_arr, 13)

In [ ]:
sorted_array = np.sort(new_arr)

In [ ]:
sorted_array

In [ ]:
arr = np.arange(24)
arr

In [ ]:
np.reshape(arr, (3,4,2))

In [ ]:
arr.reshape(6,4)

In [ ]:
# Create a NumPy array (there must be first 16 numbers starting from 0 to 16 (exclusive)) using a function arange(). Select the correct array.
np.arange(17)

In [68]:
# Consider the given Python list and follow the steps below:

L = [10, 2, 7, 8, 3, 22, 54, 12, 13, 46, 23, 25, 41]

In [74]:
np_arr = np.array(L)     # convert to np array
np_arr#

array([10,  2,  7,  8,  3, 22, 54, 12, 13, 46, 23, 25, 41])

In [79]:
sorted_array =np.sort(np_arr)

In [80]:
sorted_array

array([ 2,  3,  7,  8, 10, 12, 13, 22, 23, 25, 41, 46, 54])

In [81]:
print(sorted_array)

[ 2  3  7  8 10 12 13 22 23 25 41 46 54]


In [84]:
np.delete(np_arr, 4)

array([ 2,  3,  7,  8, 12, 13, 22, 23, 25, 41, 46, 54])

In [85]:
np.append(np_arr, 53)

array([ 2,  3,  7,  8, 10, 12, 13, 22, 23, 25, 41, 46, 54, 53])

In [89]:
np_arr.shape

(13,)

In [90]:
arr

array([[50, 45, 56, 78],
       [78, 89, 59, 90],
       [89, 78, 69, 70],
       [67, 69, 89, 70],
       [90, 89, 80, 84],
       [89, 59, 90, 78]])

In [93]:
arr[2:5, 1:4]

array([[78, 69, 70],
       [69, 89, 70],
       [89, 80, 84]])

In [96]:
 arr[-4:-1, -3:]

array([[78, 69, 70],
       [69, 89, 70],
       [89, 80, 84]])

In [97]:
# adding 3 to every element
a = np.array([7, 6, 8, 9])
print ("Adding 6 to every element:", a+6)

Adding 1 to every element: [13 12 14 15]


In [98]:
a - 4

array([3, 2, 4, 5])

In [99]:
a * 3

array([21, 18, 24, 27])

In [100]:
a ** 2

array([49, 36, 64, 81], dtype=int32)

In [101]:
a *= 2

In [102]:
a

array([14, 12, 16, 18])

In [103]:
# transpose of array
a = np.array([[3, 1, 2], [6, 5, 4], [7, 9, 8]])

In [104]:
a

array([[3, 1, 2],
       [6, 5, 4],
       [7, 9, 8]])

In [105]:
a.transpose()

array([[3, 6, 7],
       [1, 5, 9],
       [2, 4, 8]])

In [106]:
arr = np.array([1,9,8,4,5,6])
np.append(arr, 77)

array([ 1,  9,  8,  4,  5,  6, 77])

In [107]:
l = [2,3,5,4,7,6]
arr = np.append(l,10)
arr

array([ 2,  3,  5,  4,  7,  6, 10])

In [108]:
np.append(arr, [23,34,55,67])

array([ 2,  3,  5,  4,  7,  6, 10, 23, 34, 55, 67])

In [109]:
# remove an element
np.delete(arr,3)

array([ 2,  3,  5,  7,  6, 10])

In [111]:
# sorting an array of integers
np.sort(arr)

array([ 2,  3,  4,  5,  6,  7, 10])

In [112]:
#sorting an array alphabetically
arr = np.array(['Lamborghini', 'Porsche', 'Mercedes'])
np.sort(arr)

array(['Lamborghini', 'Mercedes', 'Porsche'], dtype='<U11')

In [115]:
#sorting a 2-D array
arr = np.array([
    [5, 7, 8],
    [6, 2, 3]
])
arr

array([[5, 7, 8],
       [6, 2, 3]])

In [116]:
np.sort(arr)

array([[5, 7, 8],
       [2, 3, 6]])

In [117]:
#Find the indexes where the value is 4:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

In [118]:
np.where(arr == 4)

(array([3, 5, 6], dtype=int64),)

In [120]:
np.where(arr % 2 != 0)

(array([0, 2, 4], dtype=int64),)

In [121]:
# Get the first element from the following array:
import numpy as np
arr = np.array([9, 8, 4, 5])

In [122]:
arr[0]

9

In [123]:
arr = np.array([[1,2,3,4,5],
[6,7,8,9,10]])

In [124]:
arr[0][1]

2

In [125]:
arr[0,1]

2

In [126]:
# Slicing elements from index 3 to index 7 in the following array:
arr = np.array([22, 81, 23, 34, 56, 63, 71])

In [127]:
arr[3:7]

array([34, 56, 63, 71])

In [128]:
# Return every other element from the entire array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


In [129]:
#Slicing 2-D Arrays
# From the second element, slice elements from index 1 to index 4 (not included):

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

In [132]:
arr[1,1:4]

array([7, 8, 9])

In [133]:
#From both elements, return index 2:
arr = np.array([[1, 2, 4, 5, 3],
                [9, 8, 7, 6, 1]])

In [136]:
arr[:,2]

array([4, 7])

In [137]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [138]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [139]:
arr[:, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [140]:
# Slice from the index 3 from the end to index 1 from the end:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [141]:
arr[-3:-1]

array([5, 6])

In [143]:
#printing the last two elements
arr = np.array([0, 1, 2, 3, 6, 7, 8, 9])
arr[-2:]

array([8, 9])

In [144]:
arr[-3:3:-1]

array([7, 6])

In [148]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [149]:
np.reshape(arr, (5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])